In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('Datasets/Training.csv')

In [4]:
dataset.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [5]:
dataset.shape

(4920, 133)

In [6]:
dataset['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [8]:
X = dataset.drop('prognosis', axis=1)
y = dataset['prognosis']

In [10]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

In [13]:
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

In [14]:
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    'SVC': SVC(kernel='linear', random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Naive Bayes': MultinomialNB()
}

for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    
    print(f"{model_name} Accuracy: {accuracy:.2f}")
    print(f"{model_name} Confusion Matrix:\n{cm}\n")
    print(np.array2string(cm, separator=', '))

Random Forest Accuracy: 1.00
Random Forest Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 37]]

[[23,  0,  0, ...,  0,  0,  0],
 [ 0, 36,  0, ...,  0,  0,  0],
 [ 0,  0, 33, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 33,  0,  0],
 [ 0,  0,  0, ...,  0, 28,  0],
 [ 0,  0,  0, ...,  0,  0, 37]]
Gradient Boosting Accuracy: 1.00
Gradient Boosting Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 37]]

[[23,  0,  0, ...,  0,  0,  0],
 [ 0, 36,  0, ...,  0,  0,  0],
 [ 0,  0, 33, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 33,  0,  0],
 [ 0,  0,  0, ...,  0, 28,  0],
 [ 0,  0,  0, ...,  0,  0, 37]]
SVC Accuracy: 1.00
SVC Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 37]]

[[23,  0,  0, ...,  0,  0,  0],
 [ 0, 36,  0, ...,  0,  0,  0],
 [ 0,  0, 33, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 33,  0,  0],
 [ 0,  0,  0, ...,  0, 28,  0],
 [ 0,  0,  0, ...,  0,  0, 37]]
KNN Accuracy: 1.00
KNN Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 37]]

[[23,  0,  0, ...,  0,  0,  0],
 [ 0, 36,  0, ...,  0,  0,  0],
 [ 0,  0, 33, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 33,  0,  0],
 [ 0,  0,  0, ...,  0, 28,  0],
 [ 0,  0,  0, ...,  0,  0, 37]]
Naive Bayes Accuracy: 1.00
Naive Bayes Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 37]]

[[23,  0,  0, ...,  0,  0,  0],
 [ 0, 36,  0, ...,  0,  0,  0],
 [ 0,  0, 33, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 33,  0,  0],
 [ 0,  0,  0, ...,  0, 28,  0],
 [ 0,  0,  0, ...,  0,  0, 37]]

In [15]:
svc = SVC(kernel='linear', random_state=42)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

In [16]:
import pickle
pickle.dump(svc, open('Models/model.pkl', 'wb'))

In [20]:
svc = pickle.load(open('Models/model.pkl', 'rb'))
print("Actual Label : ", svc.predict(X_test.iloc[0].values.reshape(1, -1)))
print("Predicted Label : ", y_test[0])

Actual Label :  [2]
Predicted Label :  2

d:\Medicine Recommendation System\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

## Recommendation System

In [53]:
sys_des = pd.read_csv('Datasets/symtoms_df.csv')
precautions = pd.read_csv('Datasets/precautions_df.csv')
workout_data = pd.read_csv('Datasets/workout_df.csv')
description = pd.read_csv('Datasets/description.csv')
medications = pd.read_csv('Datasets/medications.csv')
diets = pd.read_csv('Datasets/diets.csv')

In [31]:
sys_des.head()

,Unnamed: 0,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
0,0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches
1,1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN
2,2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN
3,3,Fungal infection,itching,skin_rash,dischromic _patches,NaN
4,4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN

In [32]:
disease_dict = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 
                14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 
                17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 
                7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 
                29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 
                19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 
                36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 
                18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 
                25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 
                2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}
symtoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 
                'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 
                'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 
                'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 
                'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 
                'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 
                'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 
                'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 
                'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 
                'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 
                'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 
                'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 
                'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 
                'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 
                'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 
                'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 
                'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 
                'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 
                'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 
                'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 
                'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 
                'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 
                'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 
                'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 
                'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 
                'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 
                'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 
                'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 
                'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}

In [33]:
def get_prediction(symtoms) :
    input_vector = np.zeros(len(symtoms_dict))
    
    for item in symtoms:
        input_vector[symtoms_dict[item]] = 1
    
    return disease_dict[svc.predict([input_vector])[0]]

In [40]:
symptoms = input("Enter Your Symptoms : ").lower()
patient_symptoms = [s.strip() for s in symptoms.split(',')]

patient_symptoms = [sym.strip() for sym in patient_symptoms]
patient_symptoms

['itching']

In [43]:
predicted_disease = get_prediction(patient_symptoms)
print(f"Predicted Disease: {predicted_disease}")

Predicted Disease: Fungal infection

d:\Medicine Recommendation System\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [54]:
def helper(disease) :
    
    desc = description[description["Disease"] == disease]["Description"]
    
    desc = " ".join([i for i in desc])
    
    precaution = precautions[precautions["Disease"] == disease][
        ["Precaution_1" , "Precaution_2" , "Precaution_3" , "Precaution_4"]
    ]
    precaution = [i for i in precaution.values]
    
    symptoms_ = sys_des[sys_des["Disease"] == disease][
        ["Symptom_1" , "Symptom_2" , "Symptom_3" , "Symptom_4"]
    ]
    symptoms_list = [i for i in symptoms_.values]
    
    medicine = medications[medications["Disease"] == disease]["Medication"]
    medicine = [i for i in medicine.values]
  
    diet = diets[diets["Disease"] == disease]["Diet"]
    diet = [i for i in diet.values]
  
    workout = workout_data[workout_data["disease"] == disease]["workout"]
    workout = [i for i in workout.values]

    return desc , precaution , medicine , diet , workout , symptoms_list

In [55]:
desc , precaution , medicine , diet , workout , symptoms = helper(predicted_disease)

In [58]:
print("Description:")
print(desc)

Description:
Fungal infection is a common skin condition caused by fungi.

In [59]:
print("Precautions:")

j = 1

for i in precaution[0]:
    print(j , ": " , i)
    j += 1

Precautions:
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths

In [60]:
print("Related symptoms:")

j = 1

for i in symptoms[0]:
    print(j , " : " , i)
    j += 1

Related symptoms:
1  :  itching
2  :   skin_rash
3  :   nodal_skin_eruptions
4  :   dischromic _patches

In [61]:
print("Medications:")

for i in medicine:
    print(i)

Medications:
['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']

In [62]:
print("Diets:")

for i in diet:
    print(i)

Diets:
['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']

In [64]:
print("Workouts:")

j = 1

for i in workout:
    print(j , ": " , i)
    j += 1

Workouts:
1 :  Avoid sugary foods
2 :  Consume probiotics
3 :  Increase intake of garlic
4 :  Include yogurt in diet
5 :  Limit processed foods
6 :  Stay hydrated
7 :  Consume green tea
8 :  Eat foods rich in zinc
9 :  Include turmeric in diet
10 :  Eat fruits and vegetables